# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.0
MAINTAINER DigitalBank
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY /var/jenkins_home/workspace/DigitalBank/target/bank##2.1.0.local.war /usr/local/tomcat/
